export const dataset = [
    {
      Laptop: 59,
      Desktop: 57,
      MobilePhone: 86,
      SmartWatch: 21,
      month: 'Jan',
    },
    {
      Laptop: 50,
      Desktop: 52,
      MobilePhone: 78,
      SmartWatch: 28,
      month: 'Feb',
    },
    {
      Laptop: 47,
      Desktop: 53,
      MobilePhone: 106,
      SmartWatch: 41,
      month: 'Mar',
    },
    {
      Laptop: 54,
      Desktop: 56,
      MobilePhone: 92,
      SmartWatch: 73,
      month: 'Apr',
    },
    {
      Laptop: 57,
      Desktop: 69,
      MobilePhone: 92,
      SmartWatch: 99,
      month: 'May',
    },
    {
      Laptop: 60,
      Desktop: 63,
      MobilePhone: 103,
      SmartWatch: 144,
      month: 'June',
    },
    {
      Laptop: 59,
      Desktop: 60,
      MobilePhone: 105,
      SmartWatch: 319,
      month: 'July',
    },
    {
      Laptop: 65,
      Desktop: 60,
      MobilePhone: 106,
      SmartWatch: 249,
      month: 'Aug',
    },
    {
      Laptop: 51,
      Desktop: 51,
      MobilePhone: 95,
      SmartWatch: 131,
      month: 'Sept',
    },
    {
      Laptop: 60,
      Desktop: 65,
      MobilePhone: 97,
      SmartWatch: 55,
      month: 'Oct',
    },
    {
      Laptop: 67,
      Desktop: 64,
      MobilePhone: 76,
      SmartWatch: 48,
      month: 'Nov',
    },
    {
      Laptop: 61,
      Desktop: 70,
      MobilePhone: 103,
      SmartWatch: 25,
      month: 'Dec',
    },
  ];
  