export const userColumns = [
    { field: "id", headerName: "ID", width: 150 },
    {
      field: "user",
      headerName: "User",
      width: 230,
      renderCell: (params) => {
        return (
          <div className="cellWithImg">
            <img className="cellImg" src={params.row.img} alt="avatar" />
            {params.row.username}
          </div>
        );
      },
    },
    {
      field: "email",
      headerName: "Email",
      width: 230,
    },
  
    {
      field: "age",
      headerName: "Age",
      width: 100,
    },
    {
      field: "status",
      headerName: "Status",
      width: 160,
      renderCell: (params) => {
        return (
          <div className={`cellWithStatus ${params.row.status}`}>
            {params.row.status}
          </div>
        );
      },
    },
  ];
  
  //temporary data
  export const userRows = [
    {
      id: 1,
      username: "harry",
      img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      status: "active",
      email: "1hogwartz@gmail.com",
      age: 35,
    },
    {
      id: 2,
      username: "voldermort",
      img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      email: "2hogwartz@gmail.com",
      status: "disabled",
      age: 42,
    },
    {
      id: 3,
      username: "dumbledore",
      img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      email: "3hogwartz@gmail.com",
      status: "active",
      age: 45,
    },
    {
      id: 4,
      username: "hermione",
      img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      email: "4hogwartz@gmail.com",
      status: "active",
      age: 16,
    },
    {
      id: 5,
      username: "snape",
      img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      email: "5hogwartz@gmail.com",
      status: "disabled",
      age: 22,
    },
    {
      id: 6,
      username: "ron",
      img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      email: "6hogwartz@gmail.com",
      status: "active",
      age: 15,
    },
    {
      id: 7,
      username: "hagrid",
      img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      email: "7hogwartz@gmail.com",
      status: "disabled",
      age: 44,
    },
    {
      id: 8,
      username: "neville",
      img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      email: "8hogwartz@gmail.com",
      status: "active",
      age: 36,
    },
    {
      id: 9,
      username: "umbridge",
      img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      email: "hogwartz@gmail.com",
      status: "active",
      age: 65,
    },
    {
      id: 10,
      username: "umbridge",
      img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      email: "hogwartz@gmail.com",
      status: "active",
      age: 65,
    },
    {
        id: 11,
        username: "umbridge",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "hogwartz@gmail.com",
        status: "active",
        age: 65,
      },
      {
        id: 12,
        username: "umbridge",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "hogwartz@gmail.com",
        status: "active",
        age: 65,
      },
      {
        id: 13,
        username: "umbridge",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "hogwartz@gmail.com",
        status: "active",
        age: 65,
      },
      {
        id: 14,
        username: "umbridge",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "hogwartz@gmail.com",
        status: "active",
        age: 65,
      },
      {
        id: 15,
        username: "harry",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        status: "active",
        email: "email@gmail.com",
        age: 35,
      },
      {
        id: 16,
        username: "voldermort",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "2hogwartz@gmail.com",
        status: "disabled",
        age: 42,
      },
      {
        id: 17,
        username: "dumbledore",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "3hogwartz@gmail.com",
        status: "active",
        age: 45,
      },
      {
        id: 18,
        username: "hermione",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "email@gmail.com",
        status: "active",
        age: 16,
      },
      {
        id: 19,
        username: "snape",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "5hogwartz@gmail.com",
        status: "disabled",
        age: 22,
      },
      {
        id: 20,
        username: "ron",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "email@gmail.com",
        status: "active",
        age: 15,
      },
      {
        id: 21,
        username: "hagrid",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "7hogwartz@gmail.com",
        status: "disabled",
        age: 44,
      },
      {
        id: 22,
        username: "neville",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "8hogwartz@gmail.com",
        status: "active",
        age: 36,
      },
      {
        id: 23,
        username: "umbridge",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "email@gmail.com",
        status: "active",
        age: 65,
      },
      {
        id: 24,
        username: "umbridge",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "hogwartz@gmail.com",
        status: "active",
        age: 65,
      },
      {
        id: 25,
        username: "umbridge",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "hogwartz@gmail.com",
        status: "active",
        age: 65,
    },
    {
        id: 26,
        username: "umbridge",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "email@gmail.com",
        status: "active",
        age: 65,
    },
    {
        id: 27,
        username: "umbridge",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "hogwartz@gmail.com",
        status: "active",
        age: 65,
    },
    {
        id: 28,
        username: "umbridge",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "hogwartz@gmail.com",
        status: "active",
        age: 65,
    },
    {
        id: 29,
        username: "umbridge",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "hogwartz@gmail.com",
        status: "active",
        age: 65,
    },
    {
        id: 30,
        username: "umbridge",
        img: "https://images.pexels.com/photos/406014/pexels-photo-406014.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
        email: "hogwartz@gmail.com",
        status: "active",
        age: 65,
    },
        
  ];